// Code generated by mockery v2.0.0-alpha.2. DO NOT EDIT.

package mocks

import (
	generate "github.com/clarafu/release-me/generate"
	mock "github.com/stretchr/testify/mock"
)

// Template is an autogenerated mock type for the Template type
type Template struct {
	mock.Mock
}

// Render provides a mock function with given fields: sections
func (_m *Template) Render(sections []generate.Section) error {
	ret := _m.Called(sections)

	var r0 error
	if rf, ok := ret.Get(0).(func([]generate.Section) error); ok {
		r0 = rf(sections)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
